piVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels: # these labels are deployment labels
    app: mongodb
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: mongodb
      project: roboshop
      tier: db
  template:
    metadata:
      labels: # these labels are pod labels
        app: mongodb
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.deployment.imageURL}}:{{ .Values.deployment.imageVersion}}"
        imagePullPolicy: Always